##########################################################################
# Makefile for the 'Compilerbau' lecture
##########################################################################

## Run 'make' or 'make help' to display commonly used targets. Targets for
## individual files also exist but should only be used if you know what
## you are doing.

## NOTE:
## The pdf slides that can be generated for certain chapters are named by
## taking the relative path of the respective source file and replacing
## any '/' with an '_' (e.g. A/B/C -> A_B_C). This must be reversable in
## order to find the prerequisites for each output file. Therefore, any
## subdirectory of the $(SRC_DIR) directory must NOT contain an '_'.

#-------------------------------------------------------------------------
# Tools
#-------------------------------------------------------------------------
## Define tools to process various types of source files. By default, a
## custom Docker image will be used. To create this image, run:
## make create-docker-image
##
## Launching tools via a Docker container: make TARGET
## Launch the tools directly:              export DOCKER=false; make TARGET
##
## Note: LaTeX needs to be called in the folder of the .tex file to
## be processed. In the rule that generates images from tex files, the
## variable "$<" is set to the current .tex file (incl. path in the working
## directory). Therefore, the working directory for the Docker container is
## set to the folder of the current .tex file. When called directly, we
## need to first change-dir to this folder.
ifneq ($(DOCKER), false)
DOCKER_IMAGE      = alpine-pandoc-hugo
DOCKER_COMMAND    = docker run --rm -i
DOCKER_USER       = -u "$(shell id -u):$(shell id -g)"
DOCKER_VOLUME     = -v "$(shell pwd):/data" -w "/data"
DOCKER_TEX_VOLUME = -v "$(dir $(realpath $<)):/data" -w "/data"

PANDOC = $(DOCKER_COMMAND) $(DOCKER_VOLUME)     $(DOCKER_USER) --entrypoint="pandoc" $(DOCKER_IMAGE)
HUGO   = $(DOCKER_COMMAND) $(DOCKER_VOLUME)     $(DOCKER_USER) --entrypoint="hugo"   $(DOCKER_IMAGE)
DOT    = $(DOCKER_COMMAND) $(DOCKER_VOLUME)     $(DOCKER_USER) --entrypoint="dot"    $(DOCKER_IMAGE)
LATEX  = $(DOCKER_COMMAND) $(DOCKER_TEX_VOLUME) $(DOCKER_USER) --entrypoint="latex"  $(DOCKER_IMAGE)
else
PANDOC = pandoc
HUGO   = hugo
DOT    = dot
LATEX  = cd $(dir $(realpath $<)) && latex
endif

## Data-Dir: Path to the Git submodule of Pandoc-Lecture
## Resource-Path: Where to search for bib files and other resources?
##
## Note: If Pandoc is used via a Docker container, DATADIR must be the
## working directory or a subdirectory, as the working directory will
## be mounted into the Docker container! References to a parent directory
## of the working directory therefore will not work when using a Docker
## container!
PANDOC_DIRS = --data-dir=pandoc --resource-path=".:pandoc"

## Define options for generating images from ".tex" files
LATEX_ARGS = -shell-escape

## Define options for generating images from ".dot" files
DOT_ARGS = -Tpng

## Define options to be used by Hugo
## local.yaml allows to override settings in config.yaml
HUGO_LOCAL = $(wildcard local.yaml)
HUGO_ARGS  = --config config.yaml,$(HUGO_LOCAL)

#-------------------------------------------------------------------------
# I/O Directories
#-------------------------------------------------------------------------

## Top level directory for source files
SRC_DIR = markdown

## Top level directory for temporary files
TEMP_DIR      = temp
HUGO_TEMP_DIR = resources

## Top level directory for generated image files
IMAGES_OUTPUT_DIR = $(TEMP_DIR)/images

## Top level directory for temporary files used to generate website (input for Hugo)
WEB_INTERMEDIATE_DIR = $(TEMP_DIR)/content

## Top level directory for temporary files used in slides generation
SLIDES_INTERMEDIATE_DIR = $(TEMP_DIR)/slides

## Output directory generated by Hugo
WEB_OUTPUT_DIR = docs

## Output directory for generated slides
SLIDES_OUTPUT_DIR = pdf

#-------------------------------------------------------------------------
# Helper lists
#-------------------------------------------------------------------------

## TeX source and target files
TEX_SOURCES        = $(shell find $(SRC_DIR) -type f -iname '*.tex')
TEX_INTERMEDIATE   = $(patsubst $(SRC_DIR)/%,$(IMAGES_OUTPUT_DIR)/%, $(TEX_SOURCES))
TEX_TARGETS        = $(patsubst $(SRC_DIR)/%.tex,$(IMAGES_OUTPUT_DIR)/%.png, $(TEX_SOURCES))
WEB_TEX_TARGETS    = $(patsubst $(SRC_DIR)/%.tex,$(WEB_INTERMEDIATE_DIR)/%.png, $(TEX_SOURCES))
SLIDES_TEX_TARGETS = $(patsubst $(SRC_DIR)/%.tex,$(SLIDES_INTERMEDIATE_DIR)/%.png, $(TEX_SOURCES))

## Dot source and target files
DOT_SOURCES        = $(shell find $(SRC_DIR) -type f -iname '*.dot')
DOT_TARGETS        = $(patsubst $(SRC_DIR)/%.dot,$(IMAGES_OUTPUT_DIR)/%.png, $(DOT_SOURCES))
WEB_DOT_TARGETS    = $(patsubst $(SRC_DIR)/%.dot,$(WEB_INTERMEDIATE_DIR)/%.png, $(DOT_SOURCES))
SLIDES_DOT_TARGETS = $(patsubst $(SRC_DIR)/%.dot,$(SLIDES_INTERMEDIATE_DIR)/%.png, $(DOT_SOURCES))

## Standalone image sources and targets
STANDALONE_SOURCES         = $(shell find $(SRC_DIR) -type f -iname '*.png')
STANDALONE_TARGETS         = $(patsubst $(SRC_DIR)/%,$(IMAGES_OUTPUT_DIR)/%, $(STANDALONE_SOURCES))
WEB_STANDALONE_TARGETS     = $(patsubst $(SRC_DIR)/%,$(WEB_INTERMEDIATE_DIR)/%, $(STANDALONE_SOURCES))
SLIDES_STANDALONE_TARGETS  = $(patsubst $(SRC_DIR)/%,$(SLIDES_INTERMEDIATE_DIR)/%, $(STANDALONE_SOURCES))

## Image targets for web and slides
WEB_IMAGE_TARGETS    = $(WEB_TEX_TARGETS) $(WEB_DOT_TARGETS) $(WEB_STANDALONE_TARGETS)
SLIDES_IMAGE_TARGETS = $(SLIDES_TEX_TARGETS) $(SLIDES_DOT_TARGETS) $(SLIDES_STANDALONE_TARGETS)

## Markdown source and target files
WEB_MARKDOWN_SOURCES = $(shell find $(SRC_DIR) -type f -iname '*.md')
WEB_MARKDOWN_TARGETS = $(WEB_MARKDOWN_SOURCES:$(SRC_DIR)%=$(WEB_INTERMEDIATE_DIR)%)

## Source and target files for slides
## NOTE: The name for the target pdf file is generated from the relative
## path under $(SRC_DIR) with '/' substituted by '_'. Directories containing
## a .noslides file will not be considerd for slides generation.
SLIDES_EXCLUDE_DIRS     = $(dir $(shell find $(SRC_DIR) -type f -iname '.noslides'))
SLIDES_MARKDOWN_SOURCES = $(filter-out $(addsuffix %, $(SLIDES_EXCLUDE_DIRS)), $(shell find $(SRC_DIR) -type f -iname 'index.md'))
SLIDES_MARKDOWN_TARGETS = $(SLIDES_MARKDOWN_SOURCES:$(SRC_DIR)%=$(SLIDES_INTERMEDIATE_DIR)%)
SLIDES_PDF_TARGETS      = $(addprefix $(SLIDES_OUTPUT_DIR)/,$(subst /,_, $(patsubst $(SRC_DIR)/%/index.md,%.pdf, $(SLIDES_MARKDOWN_SOURCES))))
SLIDES_SHORT_TARGETS    = $(patsubst $(SLIDES_OUTPUT_DIR)/%.pdf,%,$(SLIDES_PDF_TARGETS))

## Readings data template
READINGS = data/readings.yaml
BIBTEX   = cb.bib

#-------------------------------------------------------------------------
# Secondary Expansion
#-------------------------------------------------------------------------

## Enable secondary expansion for subsequent targets. This allows the use
## of automatic variables like '@' in the prerequisite definitions by
## expanding twice (e.g. $$(VAR)). For normal variable references (e.g.
## $(VAR)) the expansion behaviour is unchanged as the second expansion
## has no effect on an already fully expanded reference.

.SECONDEXPANSION:

#-------------------------------------------------------------------------
# Phony Targets
#-------------------------------------------------------------------------

.DEFAULT_GOAL:=help

##@ Helpers

## Display help
.PHONY: help
help:  ## Display this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

.PHONY: list-slides
list-slides: ## List available targets for individual slides
	$(foreach target,$(SLIDES_SHORT_TARGETS), $(info $(target)))
	@: ## Suppress 'Nothing to be done for ...' message

##@ Building

## Make everything
.PHONY: all
all: slides web ## Make everything

## Create all slides
.PHONY: slides
slides: $(SLIDES_PDF_TARGETS) ## Create all slides

## Generate pdf slides (shortened target name for convenience)
.PHONY: $(SLIDES_SHORT_TARGETS)
$(SLIDES_SHORT_TARGETS): $$(patsubst %,$(SLIDES_OUTPUT_DIR)/%.pdf,$$@)

## Create website
.PHONY: web
web: $(WEB_MARKDOWN_TARGETS) $(WEB_IMAGE_TARGETS) $(READINGS) $(HUGO_LOCAL) ## Create website
	$(HUGO) $(HUGO_ARGS)

## Build Docker image "alpine-pandoc-hugo"
.PHONY: docker
docker: ## Build Docker image "alpine-pandoc-hugo"
	cd .github/actions/alpine-pandoc-hugo && make clean all

##@ Cleanup

.PHONY: clean-all
clean-all: clean-temp ## Clean up all generated files and directories
	rm -rf $(SLIDES_OUTPUT_DIR) $(WEB_OUTPUT_DIR) $(READINGS)

.PHONY: clean-temp
clean-temp: ## Clean up all intermediate files and directories
	rm -rf $(TEMP_DIR) $(HUGO_TEMP_DIR)

.PHONY: distclean
distclean: clean-all ## Same as clean-all

.PHONY: clean
clean: clean-temp ## Same as clean-temp

##@ New Elements

## Create new lecture stub based on archetype
## Use all sections and the page name, but leave out "content/" and "index.md".
## Example: "markdown/topic/subtopic/lecture/index.md" becomes "topic/subtopic/lecture"
## 1. "make new_chapter TOPIC=topic"
## 2. "make new_chapter TOPIC=topic/subtopic"
## 3. "make new_lecture-bc TOPIC=topic/subtopic/lecture"
TOPIC ?=

PHONY: new_chapter
new_chapter: ## Create new chapter
	$(HUGO) new -c "$(ORIG_CONTENT)/" -k chapter $(TOPIC)

PHONY: new_lecture-bc
new_lecture-bc: ## Create new lecture for BC
	$(HUGO) new -c "$(ORIG_CONTENT)/" -k lecture-bc $(TOPIC)

PHONY: new_lecture-cg
new_lecture-cg: ## Create new lecture for Carsten
	$(HUGO) new -c "$(ORIG_CONTENT)/" -k lecture-cg $(TOPIC)

PHONY: new_assignment
new_assignment: ## Create new assignment
	$(HUGO) new -c "$(ORIG_CONTENT)/" -k assignment $(TOPIC)

#-------------------------------------------------------------------------
# File Targets
#-------------------------------------------------------------------------

## Canned recipe for creating output folder
define create-folder
mkdir -p $(dir $@)
endef

## Canned recipe for creating output folder and copy output file
define create-dir-and-copy
mkdir -p $(dir $@)
cp $< $@
endef

## Create readings data template
$(READINGS): $(BIBTEX)
	$(PANDOC) -s -f biblatex -t markdown $< -o $@

## Copy tex source files to $(IMAGES_OUTPUT_DIR)
## Note: This is necessary because latex generates output in the directory
##       it is called in and we do not want the $(SRC_DIR) littered with
##       temporary files.
$(TEX_INTERMEDIATE): $(IMAGES_OUTPUT_DIR)/%: $(SRC_DIR)/%
	$(create-dir-and-copy)

## Create images from tex files
$(TEX_TARGETS): %.png: %.tex
	$(LATEX) $(LATEX_ARGS) $(notdir $<)

## Create images from dot files
$(DOT_TARGETS): $(IMAGES_OUTPUT_DIR)/%.png: $(SRC_DIR)/%.dot
	$(create-folder)
	$(DOT) $(DOT_ARGS) $< -o $@

## Copy standalone images to $(IMAGES_OUTPUT_DIR)
$(STANDALONE_TARGETS): $(IMAGES_OUTPUT_DIR)/%: $(SRC_DIR)/%
	$(create-dir-and-copy)

## Copy image files to $(WEB_INTERMEDIATE_DIR)
$(WEB_IMAGE_TARGETS): $(WEB_INTERMEDIATE_DIR)/%: $(IMAGES_OUTPUT_DIR)/%
	$(create-dir-and-copy)

## Process markdown with pandoc (preprocessing for hugo)
$(WEB_MARKDOWN_TARGETS): $(WEB_INTERMEDIATE_DIR)/%: $(SRC_DIR)/%
	$(create-folder)
	$(PANDOC) $(PANDOC_DIRS) -d hugo $< -o $@

## Copy image files to $(SLIDES_INTERMEDIATE_DIR)
$(SLIDES_IMAGE_TARGETS): $(SLIDES_INTERMEDIATE_DIR)/%: $(IMAGES_OUTPUT_DIR)/%
	$(create-dir-and-copy)

## Copy markdown files to $(SLIDES_INTERMEDIATE_DIR)
$(SLIDES_MARKDOWN_TARGETS): $(SLIDES_INTERMEDIATE_DIR)/%: $(SRC_DIR)/%
	$(create-dir-and-copy)

## Generate pdf slides
## Prerequisites are the lessons 'index.md' and the images in the 'images'
## subfolder.
## NOTE: The prerequisites for the images must be added after the 'index.md'
## so that '$<' contains the right input file for pandoc.
$(SLIDES_PDF_TARGETS): $$(patsubst $(SLIDES_OUTPUT_DIR)/%.pdf,$(SLIDES_INTERMEDIATE_DIR)/%/index.md, $$(subst _,/,$$@))
	$(create-folder)
	$(PANDOC) $(PANDOC_DIRS) -d slides $< -o $@
$(SLIDES_PDF_TARGETS): $$(filter $$(patsubst $(SLIDES_OUTPUT_DIR)/%.pdf,$(SLIDES_INTERMEDIATE_DIR)/%, $$(subst _,/,$$@))%, $(SLIDES_IMAGE_TARGETS))

