name: GitHub Preview

on:
  # push on master branch
  push:
    branches: [master]
  # triggered manually
  workflow_dispatch:

jobs:
  gfm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cagix/pandoc-lecture-zen@master
        with:
          mktarget: gfm
          pandoc_data: .pandoc
          metadata: ki.yaml
          publish_dir: _gfm
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _gfm
          publish_branch: _gfm
          force_orphan: true
