name: Handout (Docsify plus PDF)

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lecture-repo (fully)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Fetch cagix/pandoc-lecture-zen@master
        run: make update_tooling

      - name: Build materials
        run: make handout

      - name: Publish materials
        run: make publish_orphan
