name: Handout (Docsify plus PDF)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: handout
      publish_branch: _w26
