name: TESTS

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_beamer:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: beamer

  test_docsify:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: docsify

  test_pdf:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: pdf
