name: TESTS

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_beamer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lecture-repo (fully)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch cagix/pandoc-lecture-zen@master
        run: make update_tooling

      - name: Build materials
        run: make beamer

  test_docsify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lecture-repo (fully)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch cagix/pandoc-lecture-zen@master
        run: make update_tooling

      - name: Build materials
        run: make docsify

  test_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lecture-repo (fully)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch cagix/pandoc-lecture-zen@master
        run: make update_tooling

      - name: Build materials
        run: make pdf
